### ISSUE TITLE
Request: Add support for layering

### ISSUE THREAD

**Issue by billchurch** [Cweili/svelte-fa#116]
FontAwesome supports layering, however there doesn't seem to be a way to enable it through this module.

Reference: https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/layering

Example Code:

```
<script>
	import Fa from 'svelte-fa'
	import { faBell, faExclamation } from '@fortawesome/free-solid-svg-icons';
</script>
<span class="fa-layers fa-fw fa-lg" style="background: grey;">
	<Fa icon={faBell} style='color: white' class="fas" />
	<Fa icon={faExclamation} size="xs" class="fas" style='color: red;'/>
</span>
```

This should produce a layered version where the exclamation is over the bell, instead it produces an exclamation next to the bell.

![image](https://user-images.githubusercontent.com/1668075/130639648-a3bf7b58-bee6-486c-950a-5eb68fe71314.png)

**Comment by Cweili** [comment]
Released in v2.3.3
