### ISSUE TITLE
import not found: FaLayers

### ISSUE THREAD

**Issue by www-chique** [Cweili/svelte-fa#130]
When importing FaLayers

```
import Fa, { FaLayers } from "svelte-fa";
```

It shows

>SyntaxError: import not found: FaLayers

**Comment by Cweili** [comment]
This issue is closed due to not being active. Please feel free to open it again (for the author) or create a new one and reference this (for others) if you have further questions.

**Comment by VinceERS** [comment]
Here's an example repl where the problem is also happening: https://svelte.dev/repl/d150cdddb9ed4337af690070c7d3c855?version=3.46.4
