### ISSUE TITLE
Doesn't play nice with @fortawesome/fontawesome-free

### ISSUE THREAD

**Issue by blake-regalia** [Cweili/svelte-fa#142]
It seems that after a recent package upgrade, if your page globally imports the fontawesome-free library (i.e., separate from svelte), the package will replace anything with the "fa" class including svg tags. The result is now all the svgs created by svelte-fa are getting their innards replaced with fontawesome's flashing error icon indicator which alternates between "?" and "!"
<img width="23" alt="Screen Shot 2021-10-27 at 14 52 59" src="https://user-images.githubusercontent.com/1456400/139153096-16e261b7-c4cb-4082-8707-d5c9fdb56ede.png">

Diving into the code, if I remove the "fa" class from the svelte-fa component, everything works fine. Is this class really necessary on the svg tag? It is causing issues for pages that already include the fontawesome library.

**Comment by Cweili** [comment]
Fixed in v2.4.0 [b1787f2]
