### ISSUE TITLE
No gallery - names don't match FA

### ISSUE THREAD

**Issue by king612** [Cweili/svelte-fa#170]
Since there is no gallery that I can find, how does one know what the faFlag codes are, since they apparently don't correspond to the regulare FA names. 

For example, I wanted to add a svelte-fa icon for arrow-right in FA (e.g., [here](https://fontawesome.com/search?q=arrow&s=brands%2Cregular)), but there is no corresponding faFlag for that, and the closest thing I could find was 'faArrowCircleRight'.  Also, since there's no gallery showing icons to codes, I had to rely on autocomplete and trial and error in the import statement in Svelte.

Am I missing something?

Thanks!  And great work on this!

**Comment by ErickRDev** [comment]
@king612 you should also install `@fortawesome/free-solid-svg-icons`

With that installed, you can simply:
```
<script>
  import Fa from 'svelte-fa'
  import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
</script>

<Fa icon={faArrowRight} />
```

**Comment by rafalohaki** [comment]
> @king612 you should also install `@fortawesome/free-solid-svg-icons`
> 
> With that installed, you can simply:
> 
> ```
> <script>
>   import Fa from 'svelte-fa'
>   import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
> </script>
> 
> <Fa icon={faArrowRight} />
> ```

what about faDiscord? there is be fa-discord but faDiscord is not there

**Comment by Cweili** [comment]
> > @king612 you should also install `@fortawesome/free-solid-svg-icons`
> > With that installed, you can simply:
> > ```
> > <script>
> >   import Fa from 'svelte-fa'
> >   import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
> > </script>
> > 
> > <Fa icon={faArrowRight} />
> > ```
> 
> what about faDiscord? there is fa-discord but faDiscord is not there

For faDiscord, you should install [@fortawesome/free-brands-svg-icons](https://www.npmjs.com/package/@fortawesome/free-brands-svg-icons)

**Comment by Cweili** [comment]
This issue is closed due to not being active. Please feel free to open it again (for the author) or create a new one and reference this (for others) if you have further questions.
