### ISSUE TITLE
SvelteKit/Vite Not Working

### ISSUE THREAD

**Issue by michaelusantiago** [Cweili/svelte-fa#192]
I read, followed and tried the instruction on the documentations.
1.) this example works on development mode: - _Note (SvelteKit/Vite)_
`import Fa from 'svelte-fa'
import { faFlag } from '@fortawesome/free-solid-svg-icons'`
but will **failed on build**

2.) this example cause errors on development and will not compile:
`import Fa from 'svelte-fa/src/fa.svelte'
import { faCaretDown, faCaretUp } from '@fortawesome/free-solid-svg-icons/index.es'`
even with app.d.ts set to:
`declare module '@fortawesome/free-solid-svg-icons/index.es' {
	export * from '@fortawesome/free-solid-svg-icons';
}`

**Comment by tallestlegacy** [comment]
I'm stuck on this, the project works in dev but breaks on build

**Comment by michaelusantiago** [comment]
> I'm stuck on this, the project works in dev but breaks on build I think it's a problem with FontAwesome

@tallestlegacy I solved mine already https://github.com/sveltejs/kit/issues/4454 look at my comment at the bottom

**Comment by Cweili** [comment]
@michaelusantiago @tallestlegacy Glad to see FontAwesome [mention](https://github.com/FortAwesome/Font-Awesome/pull/19041#issuecomment-1198562760) that they are willing to fix this issue in the next upcoming release. Thank you for [the solution](https://github.com/sveltejs/kit/issues/4454#issuecomment-1198836933) to this issue.

**Comment by Geeky-Mechanic** [comment]
> > I'm stuck on this, the project works in dev but breaks on build I think it's a problem with FontAwesome
> 
> @tallestlegacy I solved mine already [sveltejs/kit#4454](https://github.com/sveltejs/kit/issues/4454) look at my comment at the bottom

Thanks for linking to the issue, what worked for me was simply using the named imports for the specific module such as : `import { faEnvelope } from "@fortawesome/free-solid-svg-icons/faEnvelope";` as suggested by Rich Harris! I did not need to edit the vite.config.js file

**Comment by Cweili** [comment]
FontAwesome has got this fixed and tested and ship with 6.2.0.
