### ISSUE TITLE
Size control

### ISSUE THREAD

**Issue by Fractal-Tess** [Cweili/svelte-fa#199]
Hey there,

How is one supposed to dynamically scale/size an icon? The provided examples as well as the documentation only showcase the static sizes `(xs, lg, xl... and so on)`. What if for example, I would like the icon to fill out all the available space within the current container?

**Comment by ItzaMi** [comment]
If I'm not mistaken, `fontawesome` reacts as text, which means that its size is set by `em` measures (see [this line](https://github.com/Cweili/svelte-fa/blob/master/src/utils.js#L37) where the `size` is set and [fontawesome documentation](https://fontawesome.com/docs/web/style/size)). So... I assume that there's no easy way of doing that unless you try to set your container width / height based on your root `em`

**Comment by Cweili** [comment]
This issue is closed due to not being active. Please feel free to open it again (for the author) or create a new one and reference this (for others) if you have further questions.
