### ISSUE TITLE
False positive with `eslint-plugin-import`

### ISSUE THREAD

**Issue by leranjun** [Cweili/svelte-fa#224]
```js
import Fa from "svelte-fa";
```

This triggers `Using exported name 'Fa' as identifier for default export. eslint (import/no-named-as-default)`.

Changing the line to `import { Fa } from "svelte-fa";` would not build in SvelteKit, throwing `<Fa> is not a valid SSR component.`.

I'm not too sure what's causing this… Might be similar to import-js/eslint-plugin-import#544?

**Comment by Cweili** [comment]
Seems SvelteKit not support importing pre-compiled modules... https://github.com/Cweili/svelte-fa/issues/239#issuecomment-1319364670

**Comment by Cweili** [comment]
This issue is closed due to not being active. Please feel free to open it again (for the author) or create a new one and reference this (for others) if you have further questions.
