### ISSUE TITLE
Default Props On Component Exports

### ISSUE THREAD

**Issue by joelhickok** [Cweili/svelte-fa#24]
Nice library and good job... thanks!

The Svelte Docs [recommend](https://svelte.dev/docs#script) setting default props on components to avoid compiler warnings, and even though it's not critical,  many people appreciate using this convention.

![image](https://user-images.githubusercontent.com/6742308/74748248-6fbac480-5225-11ea-961f-41640b91fd58.png)

It looks like `color`, `primaryColor`, and  `secondaryColor` could use a default.  The docs recommend setting to `undefined` if there is no other preferred default value.

``` js
export let icon;  // no default here makes sense
export let fw = false;
export let flip = false;
export let pull = false;
export let rotate = false;
export let size = false;
export let color = undefined;  // <--- add default

// Duotone Icons
export let primaryColor = undefined;  // <--- add default
export let secondaryColor = undefined;  // <--- add default
export let primaryOpacity = 1;
export let secondaryOpacity = 0.4;
export let swapOpacity = false;
```

**Comment by Cweili** [comment]
Thanks very much! Try new version [2.1.1](https://www.npmjs.com/package/svelte-fa).
