### ISSUE TITLE
Docs for v6 usage?

### ISSUE THREAD

**Issue by danawoodman** [Cweili/svelte-fa#300]
How does one use the v6 packages from `@fortawesome/fontawesome-pro`?

I don't see any docs on this and FontAwesome's own docs are terrible.

From my understanding all the docs are using the v6 imports: https://fontawesome.com/download

**Comment by Cweili** [comment]
For v6 free packages: [official packages](https://www.npmjs.com/search?q=%40fortawesome%20svg%20icons)
For v6 pro packages: [official docs](https://fontawesome.com/v6/docs/web/setup/packages#_1-configure-access)

**Comment by Cweili** [comment]
This is indeed the v6 version. If you're unsure, you can check the version in the package.json file within the package.
The installation method for pro packages is the same as that of [official React components](https://fontawesome.com/docs/web/use-with/react/#pro). Your approach to importing them is also correct.

**Comment by danawoodman** [comment]
Ok, that was what I was being led to but FA's docs are terrible in this regard. Amazing they don't mention these packages in the v6 docs anywhere 🤦 

Thanks 👍
