### ISSUE TITLE
Add Svelte 5 runes compatibility

### ISSUE THREAD

**Issue by harryqt** [Cweili/svelte-fa#324]
When using

```javascript
export default {
    compilerOptions: {
       runes: true
    }
};
```
getting error

```
  VITE v5.1.3  ready in 431 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] /Users/harry/project5/node_modules/svelte-fa/dist/fa-layers.svelte:4:0 Cannot use `export let` in runes mode — use $props instead [plugin vite-plugin-svelte:optimize-svelte]
```

**Comment by Dibbyo456** [comment]
Fix: https://github.com/sveltejs/svelte/issues/9632#issuecomment-1825498213

**Comment by notramo** [comment]
Now it should be easy to refactor using `sv migrate svelte-5`.

**Comment by Cweili** [comment]
As @notramo mentioned, we need to maintain compatibility with the older version of Svelte. If the old syntax is no longer supported in the future, we will release a major version to support the new syntax.

If you expect to restrict the project to only support runes, you might want to try a compile option like [dynamicCompileOptions](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#dynamiccompileoptions).

Thank you for your support.
