### ISSUE TITLE
Error: Missing "./dist/fa.svelte" specifier in "svelte-fa" package

### ISSUE THREAD

**Issue by alfredjophy** [Cweili/svelte-fa#341]
I am getting this error when i updated to the latest version which was using `./src/fa.svelte`,

Im using sveltekit 4 with pnpm

**Comment by alfredjophy** [comment]
It works when
`import { Fa } from "svelte-fa";`

Maybe update the docs

**Comment by Cweili** [comment]
The correct path in the package we released is `svelte-fa/dist/fa.svelte`.

Thank you for your feedback. If you have any further questions, feel free to reopen this issue.
