### ISSUE TITLE
Possibly incorrect main in package.json

### ISSUE THREAD

**Issue by daaku** [Cweili/svelte-fa#42]
I followed the instructions at https://svelte.dev/blog/svelte-and-typescript to setup a Svelte + TypeScript project, and used this library **successfully**. But the "svelte validate" step fails with this error:

```
Error: Cannot find module 'svelte-fa' or its corresponding type declarations. (ts)
```

(Note, it can't find the module, which is why it's an error. Other components don't have type declarations, but can be found, and that results in a warning, not an error.)

I *think* this is because `main` in `package.json` is set to a svelte file, which I don't believe is correct.

**Comment by daaku** [comment]
I changed `main` to `dist/svelte-fa.js` and it fixed it.

**Comment by Cweili** [comment]
Maybe you need to build your project with rollup or webpack.

The `main` field in `package.json` is following official component [svelte-virtual-list](https://github.com/sveltejs/svelte-virtual-list/blob/v3.0.1/package.json#L5).

**Comment by daaku** [comment]
> Maybe you need to build your project with rollup or webpack.

I'm using the official rollup template mentioned in the blog: https://svelte.dev/blog/svelte-and-typescript (without any changes to the rollup configuration).

> The main field in package.json is following official component svelte-virtual-list.

I'll look into it, but it's possible that may also have it configured incorrectly to work with the newly shipped typescript support.
