### ISSUE TITLE
Not working with svelte@next

### ISSUE THREAD

**Issue by bostondevin** [Cweili/svelte-fa#67]
I get this error using svelte@next and snowpack:

Error: <Fa> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. This seems to happen with other external libraries too...

**Comment by Cweili** [comment]
Can you use codesandbox.io to provide a reproducible use case?

**Comment by Cweili** [comment]
Closed due inactivity.
