### ISSUE TITLE
Missing icons from FontAwesome

### ISSUE THREAD

**Issue by Caedan** [Cweili/svelte-fa#78]
I was looking for the **fa-linkedin** and **fa-github** icons, but couldn't find them. They are available with the free version of FontAwesome and they are kind of essential for the website I am building. Could you add them to the package or is there a way I can add these icons myself maybe?

Thanks in advance!

**Comment by Cweili** [comment]
[@fortawesome/free-brands-svg-icons](https://www.npmjs.com/package/@fortawesome/free-brands-svg-icons) should helps you.
